### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by Bubble0seven** [LakeYS/Dishorde#113]
7 Days To Die Version Alpha 18 to 19.5+

I am renting a server via pingperfect and have installed the discord intergration mod via their game panel i have followed the steps they have told me to get the bot to work using these steps below 

[Pingperfect Steps to Install](https://pingperfect.com/index.php/knowledgebase/367/7-Days-to-Die--How-To-Discord-bot-integration.html)

At one stage we had the bot actually showing as online but it was not functioning at all none of the commands worked nor did we see join or leave messages or any chat messages. 

I then tried to re install the mod and start a fresh and now the bot simply will not show as online to me in my discord and its confusing me as I have all the information in the config set correctly as shown in this gist below 

[Config FIle](https://gist.github.com/Bubble0seven/6afc035bb77945efaefbfe3d2df3461f)

Any assistance would appreciated 

Bubble0seven

**Comment by LakeYS** [comment]
Hello. PingPerfect is not officially supported or sponsored by me, so you may need to contact their support regarding issues. I can only provide debugging steps on my end: If the bot is not coming online at all, you will need to access the bot's console to check it for errors.

It may be a compatibility issue. The bot is currently using an outdated interface with Discord (This will be fixed in the next update. See #111). This may be the source of your issue, but a console check will be required to verify this.

**Comment by Bubble0seven** [comment]
thanks not wasting my time they sent me to you because it did come online at one stage but was not functioning such as no chat messages nor commands working Guess i am getting the run around from both parties.

**Comment by LakeYS** [comment]
Closing as stale for now. Feel free to comment or reach out if further assistance is needed.
